- hosts: devserver
  tasks:
  - name: mysql | Install MySQL Packages
    sudo: yes
    apt: pkg={{ item }} state=latest
    with_items:
    - mysql-server-5.6
    - mysql-client-5.6
    - python-mysqldb
